/* ============================================================================
   CANONIEKE CATALOGUS — de "bron van waarheid" voor het menu.
   Wordt bij de allereerste start in de database geladen (seed). Daarna beheer
   je alles via het beheerscherm (beheer.html) en is de DATABASE leidend.
   Velden: c=categorie, t=type, sz=maten [Small,Medium,Large], desc=omschrijving.
   Promoties (t:'promo') dragen hun samenstelling mee: pizzas/drink/side.
   ========================================================================== */
'use strict';

var STD = [11, 12.5, 13.5]; // standaard pizza S/M/L

var CATEGORIES = [
  { id: 'pizza',     label: "Pizza's",   color: '#e0533f', kind: 'food',  sort: 1 },
  { id: 'pasta',     label: "Pasta's",   color: '#d98a2b', kind: 'food',  sort: 2 },
  { id: 'burger',    label: 'Burgers',   color: '#b5713a', kind: 'food',  sort: 3 },
  { id: 'broodje',   label: 'Broodjes',  color: '#c98f4e', kind: 'food',  sort: 4 },
  { id: 'kapsalon',  label: 'Kapsalon',  color: '#9a7b3f', kind: 'food',  sort: 5 },
  { id: 'lookbrood', label: 'Lookbrood', color: '#caa14e', kind: 'food',  sort: 6 },
  { id: 'snack',     label: 'Snacks',    color: '#7fa05a', kind: 'food',  sort: 7 },
  { id: 'friet',     label: 'Frieten',   color: '#d4a629', kind: 'food',  sort: 8 },
  { id: 'dessert',   label: 'Desserts',  color: '#c56a8f', kind: 'food',  sort: 9 },
  { id: 'ijs',       label: 'IJs',       color: '#8ec5d6', kind: 'food',  sort: 10 },
  { id: 'drink',     label: 'Drankjes',  color: '#4f93c4', kind: 'drink', sort: 11 },
  { id: 'promo',     label: "Promo's",   color: '#e6b24c', kind: 'food',  sort: 12 }
];

var PRODUCTS = [
  { id: 'pz01', c: 'pizza', t: 'pizza', name: 'Margherita', desc: 'Tomaat, mozzarella, basilicum', sz: [8, 9, 10], price: 9, tag: 'Populair' },
  { id: 'pz02', c: 'pizza', t: 'pizza', name: 'Pepperoni', desc: 'Tomatensaus, mozzarella', sz: STD, price: 12.5 },
  { id: 'pz03', c: 'pizza', t: 'pizza', name: 'Soprano', desc: 'Pepperoni, salami, hete honing', sz: STD, price: 12.5, tag: 'Aanrader' },
  { id: 'pz04', c: 'pizza', t: 'pizza', name: 'Godfather', desc: 'Pepperoni, ham, spek', sz: STD, price: 12.5 },
  { id: 'pz05', c: 'pizza', t: 'pizza', name: 'Hawaiian', desc: 'Ham, ananas, rode ui', sz: STD, price: 12.5 },
  { id: 'pz06', c: 'pizza', t: 'pizza', name: 'Aloha Bay', desc: 'Kip, ananas, hete honing', sz: STD, price: 12.5 },
  { id: 'pz07', c: 'pizza', t: 'pizza', name: 'Spicy Penne Pizza', desc: 'Pittige rosa, mozzarella, parmezaan', sz: [15, 17, 19], price: 17 },
  { id: 'pz08', c: 'pizza', t: 'pizza', name: 'Bolognese', desc: 'Kaas, vleessaus, paprika', sz: STD, price: 12.5 },
  { id: 'pz09', c: 'pizza', t: 'pizza', name: 'Luna', desc: 'Kip, paprika, zwarte olijven, geitenkaas', sz: STD, price: 12.5 },
  { id: 'pz10', c: 'pizza', t: 'pizza', name: 'Mexican', desc: 'Kip, jalapeño, paprika, corn', sz: STD, price: 12.5 },
  { id: 'pz11', c: 'pizza', t: 'pizza', name: 'Bronx', desc: 'Merguez, pepperoni, meatballs', sz: STD, price: 12.5 },
  { id: 'pz12', c: 'pizza', t: 'pizza', name: 'Pollo', desc: 'Kip, basilicumpesto, tomaten', sz: STD, price: 12.5 },
  { id: 'pz13', c: 'pizza', t: 'pizza', name: 'Veggie', desc: 'Rode ui, champignons, paprika, olijven', sz: STD, price: 12.5 },
  { id: 'pz14', c: 'pizza', t: 'pizza', name: 'Kofta', desc: 'Kofta (gehakt), spek, paprika', sz: STD, price: 12.5 },
  { id: 'pz15', c: 'pizza', t: 'pizza', name: 'Italiano', desc: 'Verse tomaat, ricotta, spinazie', sz: STD, price: 12.5 },
  { id: 'pz16', c: 'pizza', t: 'pizza', name: 'Tuna', desc: 'Tonijn, zwarte olijven, rode ui', sz: STD, price: 12.5 },
  { id: 'pz17', c: 'pizza', t: 'pizza', name: 'Curry Kip', desc: 'Kip, champignons, kerriesaus', sz: STD, price: 12.5 },
  { id: 'pz18', c: 'pizza', t: 'pizza', name: 'Al Capone', desc: 'Kip, pepperoni, jalapeños, BBQ-saus', sz: STD, price: 12.5 },
  { id: 'pz19', c: 'pizza', t: 'pizza', name: 'Gotti Tuna', desc: 'Tonijn, jalapeños, ananas', sz: STD, price: 12.5 },
  { id: 'pz20', c: 'pizza', t: 'pizza', name: 'Taxi Driver', desc: 'Ham, ananas, corn', sz: STD, price: 12.5 },
  { id: 'pz21', c: 'pizza', t: 'pizza', name: 'Funghi', desc: 'Champignons, parmezaan', sz: STD, price: 12.5 },
  { id: 'pz22', c: 'pizza', t: 'pizza', name: 'RT 66', desc: 'Kip, ananas, BBQ-saus', sz: STD, price: 12.5 },
  { id: 'pz23', c: 'pizza', t: 'pizza', name: 'Marakesh', desc: 'Merguez, paprika, champignons', sz: STD, price: 12.5 },
  { id: 'pz24', c: 'pizza', t: 'pizza', name: 'Hot Kip', desc: 'Gorgonzola, kip, rode ui, pittige saus', sz: STD, price: 12.5 },
  { id: 'pz25', c: 'pizza', t: 'pizza', name: 'BBQ Kip', desc: 'Rode ui, paprika, BBQ-saus', sz: STD, price: 12.5, tag: 'Populair' },
  { id: 'pz26', c: 'pizza', t: 'pizza', name: "Kip'n Bacon", desc: 'BBQ-kip, spek, ananas', sz: STD, price: 12.5 },
  { id: 'pz27', c: 'pizza', t: 'pizza', name: 'La Mia Garlic', desc: 'Kip, spinazie, ricotta, knoflook-roomsaus', sz: STD, price: 12.5 },
  { id: 'pz28', c: 'pizza', t: 'pizza', name: 'Shawarma', desc: 'Paprika, rode ui, verse knoflook', sz: STD, price: 12.5 },
  { id: 'pz29', c: 'pizza', t: 'pizza', name: 'Greeko', desc: 'Kip, feta, zwarte olijven, oregano', sz: STD, price: 12.5 },
  { id: 'pz30', c: 'pizza', t: 'pizza', name: 'C & B Burger', desc: 'Cheddar, spek, kofta (gehakt)', sz: STD, price: 12.5 },
  { id: 'pz31', c: 'pizza', t: 'pizza', name: 'Salami', desc: 'Salami, jalapeño', sz: STD, price: 12.5 },
  { id: 'pz32', c: 'pizza', t: 'pizza', name: 'California', desc: 'Kip, spinazie, paprika', sz: STD, price: 12.5 },
  { id: 'pz33', c: 'pizza', t: 'pizza', name: 'Quattro Formaggi', desc: 'Mozzarella, ricotta, gorgonzola, goudse kaas', sz: STD, price: 12.5 },
  { id: 'pz34', c: 'pizza', t: 'pizza', name: 'Carbonara', desc: 'Spek, champignons, parmezaan, roomsaus', sz: STD, price: 12.5 },
  { id: 'pz35', c: 'pizza', t: 'pizza', name: 'Anchovies', desc: 'Ansjovis, rode ui, zwarte olijven', sz: STD, price: 12.5 },
  { id: 'pz36', c: 'pizza', t: 'pizza', name: '4 Season', desc: 'Salami, ham, paprika, champignons', sz: STD, price: 12.5 },
  { id: 'pz37', c: 'pizza', t: 'pizza', name: 'Rucola', desc: 'Kerstomaten, parmezaan, rucola', sz: STD, price: 12.5 },
  { id: 'pz38', c: 'pizza', t: 'pizza', name: 'BBQ Meatball & Bacon', desc: 'Paprika, rode ui, kaas, BBQ-saus', sz: STD, price: 12.5 },
  { id: 'pz39', c: 'pizza', t: 'pizza', name: 'Scampi', desc: 'Mozzarella, rode ui', sz: [11, 12.5, 14], price: 12.5 },
  { id: 'pz40', c: 'pizza', t: 'pizza', name: 'Frutti di Mare', desc: 'Rode ui, zwarte olijven, zeevruchten', sz: [11, 12.5, 14], price: 12.5 },
  { id: 'pz41', c: 'pizza', t: 'simple', name: 'Stromboli', desc: 'Dubbelgevouwen deeg, mozzarella, provolone', price: 8 },
  { id: 'pz42', c: 'pizza', t: 'simple', name: 'Calzone', desc: 'Met ricotta, uit de steenoven', price: 9 },
  { id: 'pa01', c: 'pasta', t: 'pasta', name: 'Scampi Roomsaus', desc: 'Champignons, tagliatelle', price: 14, tag: 'Populair' },
  { id: 'pa02', c: 'pasta', t: 'pasta', name: 'Pasta Bolognese', desc: 'Parmezaan, penne', price: 13 },
  { id: 'pa03', c: 'pasta', t: 'pasta', name: 'Kip Roomsaus', desc: 'Champignons, penne', price: 13 },
  { id: 'pa04', c: 'pasta', t: 'pasta', name: 'Kip Curry Pasta', desc: 'Champignons, penne', price: 13 },
  { id: 'pa05', c: 'pasta', t: 'pasta', name: 'Scampi Basilicumroomsaus', desc: 'Spinazie, tagliatelle', price: 14 },
  { id: 'pa06', c: 'pasta', t: 'pasta', name: "Scampi All'Arrabbiata", desc: 'Pittige tomatensaus, knoflook', price: 14 },
  { id: 'pa07', c: 'pasta', t: 'pasta', name: 'Tagliatelle Meatballs', desc: 'Tomatensaus, parmezaan', price: 13 },
  { id: 'pa08', c: 'pasta', t: 'pasta', name: 'Pasta Funghi', desc: 'Champignons, mozzarella, alfredosaus', price: 13 },
  { id: 'pa09', c: 'pasta', t: 'pasta', name: 'Creamy Veggie', desc: 'Groenten, creamy saus', price: 13 },
  { id: 'pa10', c: 'pasta', t: 'pasta', name: 'Kass & Ham', desc: 'Kaassaus, ham', price: 14 },
  { id: 'pa11', c: 'pasta', t: 'pasta', name: 'BBQ Kip Pasta', desc: 'Maïs, paprika, kaas, bbq saus', price: 14 },
  { id: 'pa12', c: 'pasta', t: 'pasta', name: 'Fruits de Mer Diavolo', desc: 'Champignons, diavolosaus', price: 15 },
  { id: 'pa13', c: 'pasta', t: 'pasta', name: 'Ravioli Ricotta & Spinazie', desc: 'Ricotta, spinazie, roomsaus', price: 14 },
  { id: 'bu01', c: 'burger', t: 'simple', name: 'Bickey Burger', desc: 'Met salade, komkommer, tomaat & saus', price: 6, tag: 'Populair' },
  { id: 'bu02', c: 'burger', t: 'simple', name: 'Crispy Kipburger', desc: 'Met salade, komkommer, tomaat & saus', price: 7.5 },
  { id: 'bu03', c: 'burger', t: 'simple', name: 'Crispyburger', desc: 'Met salade, komkommer, tomaat & saus', price: 7.5 },
  { id: 'bu04', c: 'burger', t: 'simple', name: 'Fishburger', desc: 'Met salade, komkommer, tomaat & saus', price: 7.5 },
  { id: 'bu05', c: 'burger', t: 'simple', name: 'Keftaburger', desc: 'Met salade, komkommer, tomaat & saus', price: 8 },
  { id: 'bu06', c: 'burger', t: 'simple', name: 'Mexicano Burger', desc: 'Met salade, komkommer, tomaat & saus', price: 4.5 },
  { id: 'br01', c: 'broodje', t: 'simple', name: 'Broodje Kip', desc: 'Met salade, komkommer, tomaat & saus', price: 8 },
  { id: 'br02', c: 'broodje', t: 'simple', name: 'Broodje Kafta', desc: 'Met salade, komkommer, tomaat & saus', price: 8 },
  { id: 'br03', c: 'broodje', t: 'simple', name: 'Broodje Calamari', desc: 'Met salade, komkommer, tomaat & saus', price: 9 },
  { id: 'br04', c: 'broodje', t: 'simple', name: 'Broodje Shoarma', desc: 'Met salade, komkommer, tomaat & saus', price: 8 },
  { id: 'br05', c: 'broodje', t: 'simple', name: 'Broodje Visfilet', desc: 'Met salade, komkommer, tomaat & saus', price: 9 },
  { id: 'br06', c: 'broodje', t: 'simple', name: 'Broodje Merguez', desc: 'Met salade, komkommer, tomaat & saus', price: 8 },
  { id: 'br07', c: 'broodje', t: 'simple', name: 'Broodje Mexicano', desc: 'Met salade, komkommer, tomaat & saus', price: 6 },
  { id: 'br08', c: 'broodje', t: 'simple', name: 'Broodje Falafel', desc: 'Met salade, komkommer, tomaat & saus', price: 7 },
  { id: 'ka01', c: 'kapsalon', t: 'simple', name: 'Kapsalon Kip', desc: 'Friet, kaas, salade & saus', price: 8 },
  { id: 'ka02', c: 'kapsalon', t: 'simple', name: 'Kapsalon Vlees', desc: 'Friet, kaas, salade & saus', price: 8.5 },
  { id: 'ka03', c: 'kapsalon', t: 'simple', name: 'Kapsalon Shawarma', desc: 'Friet, kaas, salade & saus', price: 8 },
  { id: 'ka04', c: 'kapsalon', t: 'simple', name: 'Kapsalon Falafel', desc: 'Friet, kaas, salade & saus', price: 7 },
  { id: 'ka05', c: 'kapsalon', t: 'simple', name: 'Kapsalon Calamari', desc: 'Friet, kaas, salade & saus', price: 9 },
  { id: 'ka06', c: 'kapsalon', t: 'simple', name: 'Kapsalon Scampi', desc: 'Friet, kaas, salade & saus', price: 9 },
  { id: 'ka07', c: 'kapsalon', t: 'simple', name: 'Kapsalon Visfilet', desc: 'Friet, kaas, salade & saus', price: 9 },
  { id: 'lb01', c: 'lookbrood', t: 'simple', name: 'Lookbrood Kaas', desc: 'Vers gebakken', price: 5 },
  { id: 'lb02', c: 'lookbrood', t: 'simple', name: 'Knoflookbrood & Kaas', desc: 'Vers gebakken', price: 6 },
  { id: 'lb03', c: 'lookbrood', t: 'simple', name: 'Lookbrood Pepperoni & Kaas', desc: 'Vers gebakken', price: 6 },
  { id: 'lb04', c: 'lookbrood', t: 'simple', name: 'Lookbrood Ham & Kaas', desc: 'Vers gebakken', price: 6 },
  { id: 'lb05', c: 'lookbrood', t: 'simple', name: 'Lookbrood Pesto & Kaas', desc: 'Vers gebakken', price: 6 },
  { id: 'lb06', c: 'lookbrood', t: 'simple', name: 'Lookbrood Cream Spinazie & Kaas', desc: 'Vers gebakken', price: 7 },
  { id: 'sn01', c: 'snack', t: 'simple', name: 'Kiptenders (3 st.)', desc: 'Krokante kipfilet', price: 3 },
  { id: 'sn02', c: 'snack', t: 'simple', name: 'Chicken Wings', desc: 'Pikant of BBQ', price: 4, tag: 'Populair' },
  { id: 'sn03', c: 'snack', t: 'simple', name: 'Mozzarellastokjes (5 st.)', desc: 'Met dip', price: 4 },
  { id: 'sn04', c: 'snack', t: 'simple', name: 'Jalapeño Kaas (5 st.)', desc: 'Pittig', price: 5 },
  { id: 'sn05', c: 'snack', t: 'simple', name: 'Kip Nuggets (5 st.)', desc: 'Met dip', price: 4 },
  { id: 'sn06', c: 'snack', t: 'simple', name: 'Calamari (7 st.)', desc: 'Gefrituurd', price: 6 },
  { id: 'sn07', c: 'snack', t: 'simple', name: 'Chicken Taquito (2 st.)', desc: 'Mexicaans', price: 5 },
  { id: 'sn08', c: 'snack', t: 'simple', name: 'Kaaskroket (2 st.)', desc: 'Klassieker', price: 3 },
  { id: 'sn09', c: 'snack', t: 'simple', name: 'Falafel (4 st.)', desc: 'Vegetarisch', price: 3 },
  { id: 'sn10', c: 'snack', t: 'simple', name: 'Moroccan Harira (soep)', desc: 'Kruidige soep', price: 4 },
  { id: 'sn11', c: 'snack', t: 'simple', name: 'Cervela', desc: 'Gefrituurd', price: 3 },
  { id: 'sn12', c: 'snack', t: 'simple', name: 'Boulet', desc: 'Gefrituurd', price: 3 },
  { id: 'sn13', c: 'snack', t: 'simple', name: 'Bami', desc: 'Gefrituurd', price: 2 },
  { id: 'sn14', c: 'snack', t: 'simple', name: 'Mexicano', desc: 'Pikante worst', price: 3 },
  { id: 'sn15', c: 'snack', t: 'simple', name: 'Visfilet op een stokje', desc: 'Gefrituurd', price: 4 },
  { id: 'fr01', c: 'friet', t: 'simple', name: 'Frieten Klein', desc: 'Vers gebakken', price: 3 },
  { id: 'fr02', c: 'friet', t: 'simple', name: 'Frieten Groot', desc: 'Vers gebakken', price: 5 },
  { id: 'de01', c: 'dessert', t: 'simple', name: 'Tiramisù', desc: 'Huisgemaakt met mascarpone', price: 5, tag: 'Aanrader' },
  { id: 'de02', c: 'dessert', t: 'simple', name: 'Cheesecake', desc: 'Romig', price: 5 },
  { id: 'de03', c: 'dessert', t: 'simple', name: 'Brownie', desc: 'Warme chocoladebrownie', price: 5 },
  { id: 'de04', c: 'dessert', t: 'simple', name: "IJsje (Ben & Jerry's)", desc: 'Diverse smaken', price: 3.5 },
  { id: 'de05', c: 'dessert', t: 'simple', name: 'Chocolate Cake', desc: 'Rijk aan chocolade', price: 5 },
  { id: 'de06', c: 'dessert', t: 'simple', name: 'Red Velvet Cake', desc: 'Klassieker', price: 5 },
  { id: 'de07', c: 'dessert', t: 'simple', name: 'Speciaal Nagerecht', desc: 'Vraag naar onze suggestie', price: 5 },
  { id: 'ijs01', c: 'ijs', t: 'simple', name: "Ben & Jerry's", desc: 'Amerikaans roomijs', price: 7, tag: 'Nieuw' },
  { id: 'ijs02', c: 'ijs', t: 'simple', name: 'Häagen-Dazs', desc: 'Premium roomijs', price: 6 },
  { id: 'ijs03', c: 'ijs', t: 'simple', name: 'Barattolino', desc: 'Italiaans roomijs', price: 6 },
  { id: 'ijs04', c: 'ijs', t: 'simple', name: 'Waterijs / kinderijs', desc: 'Nogger, Calippo & meer', price: 2 },
  { id: 'dr01', c: 'drink', t: 'drink', name: 'Cola', desc: 'Frisdrank', price: 2.5 },
  { id: 'dr02', c: 'drink', t: 'drink', name: 'Cola Zero', desc: 'Frisdrank', price: 2.5 },
  { id: 'dr03', c: 'drink', t: 'drink', name: 'Fanta', desc: 'Frisdrank', price: 2.5 },
  { id: 'dr04', c: 'drink', t: 'drink', name: 'Sprite', desc: 'Frisdrank', price: 2.5 },
  { id: 'dr05', c: 'drink', t: 'drink', name: 'Ice Tea', desc: 'Frisdrank', price: 2.5 },
  { id: 'dr06', c: 'drink', t: 'drink', name: 'Water', desc: 'Plat', price: 2 },
  { id: 'dr07', c: 'drink', t: 'drink', name: 'Bruiswater', desc: 'Sprankelend', price: 2 },
  { id: 'dr08', c: 'drink', t: 'simple', name: 'Lipton Ice Tea Peach', desc: 'Frisdrank', price: 2.5 },
  { id: 'dr09', c: 'drink', t: 'simple', name: 'Fuze Tea', desc: 'Frisdrank', price: 2.5 },
  { id: 'dr10', c: 'drink', t: 'simple', name: 'Oasis', desc: 'Fruitig', price: 2.5 },
  { id: 'dr11', c: 'drink', t: 'simple', name: 'Red Bull', desc: 'Energydrink', price: 3.5, tag: 'Nieuw' },
  { id: 'dr12', c: 'drink', t: 'simple', name: 'Monster Energy', desc: 'Energydrink', price: 3.5 },
  { id: 'dr13', c: 'drink', t: 'simple', name: 'Monster Juiced (Mango Loco)', desc: 'Energydrink', price: 3.5 },
  { id: 'dr14', c: 'drink', t: 'simple', name: 'Spa Reine', desc: 'Plat water', price: 3 },
  { id: 'dr15', c: 'drink', t: 'simple', name: 'Spa Intense', desc: 'Bruiswater', price: 3 },
  { id: 'dr16', c: 'drink', t: 'simple', name: 'Chaudfontaine', desc: 'Water', price: 3 },
  { id: 'dr17', c: 'drink', t: 'simple', name: 'Chocomel', desc: 'Zuiveldrank', price: 2.5 },
  { id: 'dr18', c: 'drink', t: 'simple', name: 'Fristi', desc: 'Zuiveldrank', price: 2.5 },
  { id: 'dr19', c: 'drink', t: 'simple', name: 'Ice Coffee Cappuccino', desc: 'IJskoffie', price: 3.5 },
  { id: 'dr20', c: 'drink', t: 'simple', name: 'Starbucks Frappuccino', desc: 'IJskoffie', price: 3.5 },
  { id: 'dr21', c: 'drink', t: 'simple', name: "Verse jus d'orange", desc: 'Vers sap', price: 3 },
  { id: 'pr01', c: 'promo', t: 'promo', name: 'Familiedeal', desc: "3 large pizza's + 3 looksaus + 1,5L frisdrank", price: 40, tag: 'Afhaal', pizzas: 3, drink: true, side: '3× looksaus + 1,5L frisdrank · enkel afhaal' },
  { id: 'pr02', c: 'promo', t: 'promo', name: 'Duo Large', desc: "2 large pizza's", price: 21, tag: 'Afhaal', pizzas: 2, side: 'Enkel afhaal' },
  { id: 'pr03', c: 'promo', t: 'promo', name: 'Duo Medium', desc: "2 medium pizza's + 2 looksaus", price: 21, tag: 'Afhaal', pizzas: 2, side: '2× looksaus · enkel afhaal' },
  { id: 'pr04', c: 'promo', t: 'promo', name: 'Trio + Wings', desc: "3 medium pizza's + 3 looksaus + 12 wings", price: 45, tag: 'Afhaal', pizzas: 3, side: '3× looksaus + 12 wings · enkel afhaal' },
  { id: 'pr05', c: 'promo', t: 'promo', name: 'Solo Large', desc: '1 large pizza + 2 looksaus + 2 frisdrank + mozzarellastokjes', price: 21, tag: 'Afhaal', pizzas: 1, drink: true, side: '2× looksaus + 2 frisdrank + mozzarellastokjes · enkel afhaal' },
  { id: 'pr06', c: 'promo', t: 'promo', name: 'Small Party', desc: "4 small pizza's + 4 looksaus + 4 frisdrank", price: 50, tag: 'Afhaal', pizzas: 4, drink: true, side: '4× looksaus + 4 frisdrank · enkel afhaal' },
  { id: 'pr07', c: 'promo', t: 'promo', name: 'Duo Deluxe', desc: "2 medium pizza's + 2 looksaus + 1,5L frisdrank", price: 26, tag: 'Afhaal', pizzas: 2, drink: true, side: '2× looksaus + 1,5L frisdrank · enkel afhaal' },
  { id: 'pr08', c: 'promo', t: 'simple', name: 'Pasta Deal', desc: "2 pasta's (kip of scampi) + 1 looksaus", price: 26, tag: 'Afhaal' }
];

module.exports = { CATEGORIES: CATEGORIES, PRODUCTS: PRODUCTS, STD: STD };
